### PR TITLE
add json support

### LINKED ISSUE #20: Json type is crashing the generator
We are starting a new project with mongoDB. I use prisma db pull on our previous database so I can keep some useful model. 
Some data were using Json because prisma couldn't understand what the value was. 
When using the generator, I received this error from the generator : 
```
Error: Json isn't support now. kind: scalar
    at Object.fakerForField (/Users/maxime/Repo/prisma-testing/node_modules/prisma-factory-generator/dist/helper.js:64:11)
    at /Users/maxime/Repo/prisma-testing/node_modules/prisma-factory-generator/dist/generator.js:146:26
    at Array.map (<anonymous>)
    at getModelDefaultValueVariableInitializer (/Users/maxime/Repo/prisma-testing/node_modules/prisma-factory-generator/dist/generator.js:143:8)
    at /Users/maxime/Repo/prisma-testing/node_modules/prisma-factory-generator/dist/generator.js:108:35
    at CodeBlockWriter._indentBlockInternal (/Users/maxime/Repo/prisma-testing/node_modules/code-block-writer/script/mod.js:263:13)
    at CodeBlockWriter.inlineBlock (/Users/maxime/Repo/prisma-testing/node_modules/code-block-writer/script/mod.js:238:14)
    at CodeBlockWriter.block (/Users/maxime/Repo/prisma-testing/node_modules/code-block-writer/script/mod.js:227:14)
    at statements (/Users/maxime/Repo/prisma-testing/node_modules/prisma-factory-generator/dist/generator.js:107:36)
    at StatementStructurePrinter.printTextOrWriterFunc (/Users/maxime/Repo/prisma-testing/node_modules/prisma-factory-generator/node_modules/ts-morph/dist/ts-morph.js:6093:13)
  ```
  
  I comment out all the Json value and the generator succeed. Though, type and enum aren't handle.
  
  Hope this helps :)

### PR DESCRIPTION
**Pull request by luisrudge**
fix https://github.com/toyamarinyon/prisma-factory-generator/issues/20

### CODE REVIEW

**Comment by luisrudge** [comment]
@toyamarinyon thanks for creating this project! It's exactly what we need. I created a PR to add support for JSON fields by using faker's [`json` data type](https://fakerjs.dev/api/datatype.html#json). Let me know if you have any questions. Also, when are you expecting to another release? We kinda need this feature haha! Thanks again!

**Comment by toyamarinyon** [comment]
@luisrudge Thank you for creating PR!! I'll check it!

**Comment by toyamarinyon** [comment]
Looks good to me. I'll merge it. Thanks 😄

**Comment by luisrudge** [comment]
@toyamarinyon awesome, thanks! when will you do a new release?

**Comment by toyamarinyon** [comment]
@luisrudge I just released it! You can find the latest release at https://github.com/toyamarinyon/prisma-factory-generator/releases/tag/v0.1.7.

**Pull request merged**
